sudo: required
services:
  - docker
before_install:
  - docker build -t sawangupta92/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sawangupta92/react-test npm run test

after_success:
  - docker build -t sawangupta92/multi-client ./client
  - docker build -t sawangupta92/multi-server ./server
  - docker build -t sawangupta92/multi-worker ./worker
  - docker build -t sawangupta92/multi-nginx ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sawangupta92/multi-client
  - docker push sawangupta92/multi-server
  - docker push sawangupta92/multi-worker
  - docker push sawangupta92/multi-nginx
